# Generated by Django 4.2.1 on 2023-06-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('ID_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AgenteInmobiliario',
            fields=[
                ('ID_agente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('ID_propiedad', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_habitaciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('ID_reunion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('ID_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_limite', models.DateField()),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ID_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_backend.cliente')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_backend.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='TareaAsignada',
            fields=[
                ('ID_tarea_asignada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_backend.agenteinmobiliario')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_backend.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='ReunionProgramada',
            fields=[
                ('ID_reunion_programada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_programacion', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_backend.cliente')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_backend.reunion')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('ID_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_backend.agenteinmobiliario')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_backend.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('ID_alquiler', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_alquiler', models.DateField()),
                ('precio_alquiler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_backend.cliente')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_backend.propiedad')),
            ],
        ),
    ]
